services:
  redis:
    image: redis:7.0-alpine
    ports:
      - "6379:6379"

  db:
    image: postgres:15.1-alpine
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      PGDATA: /var/lib/postgresql/data
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    ports:
      - "5432:5432"
