services:
  redis:
    image: redis:7.0-alpine
    ports:
      - "6379:6379"

  db:
    image: postgres:15.1-alpine
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      PGDATA: /var/lib/postgresql/data
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    ports:
      - "5432:5432"

  server:
    build: .
    environment:
      WEB_APP_BASE_URL: $WEB_APP_BASE_URL
      DATABASE_URL: $DATABASE_URL
      REDIS_URL: $REDIS_URL
      REDIS_SECRET: $REDIS_SECRET
    ports:
      - "4000:4000"
